title: Bálint Gyevnár
author: Bálint Gyevnár
email: bgyevnar@cmu.edu
description: >
  Postdoctoral research associate at Carnegie Mellon University researching the metascience of artificial intelligence.
  Previously, researching explainable multi-agent reinforcement learning.
lang: en
url: https://gbalint.me
baseurl: ""

# Adobe Fonts web project ID (https://fonts.adobe.com/my_fonts#web_projects-section)
typekit_id: eez4bau

nav:
  - title: publications
    url: /publications/
  - title: blog
    url: /blog/
  - title: news
    url: /news/

social:
  - title: email
    url: mailto:bgyevnar@cmu.edu
  - title: scholar
    url: https://scholar.google.com/citations?user=fLyES3oAAAAJ
  - title: github
    url: https://github.com/gyevnarb
  - title: linkedin
    url: https://www.linkedin.com/in/gyevnarb
  - title: cv
    url: /assets/pdf/CV.pdf

blog_name: Metascience of AI
blog_description: or how AI is changing the way we do science

permalink: /blog/:year/:title/

collections:
  news:
    output: false

defaults:
  - scope: { path: "", type: posts }
    values: { layout: post }
  - scope: { path: "" }
    values: { layout: page }

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

scholar:
  last_name: [Gyevnar, Gyevnár]
  first_name: [Balint, B., Bálint]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  query: "@*"
  group_by: year
  group_order: descending

# BibTeX fields used only by the site; stripped from the displayed BibTeX
filtered_bibtex_keywords:
  [abbr, abstract, annotation, arxiv, award, award_name, bibtex_show, blog, code, html, pdf, poster, selected, slides, supp, website]

include: [_pages]
exclude: [Gemfile, Gemfile.lock, README.md, vendor, blogger]

plugins:
  - jekyll-scholar
  - jekyll-feed
  - jekyll-sitemap
